### ISSUE TITLE
在使用red或satori协议链接qq时会出现1006错误

### ISSUE THREAD

**Issue by TOW2A** [idranme/koishi-plugin-fish-speech-online#6]
```
2024-07-14 04:44:59 [I] market Yarn 4.1.1
2024-07-14 04:45:00 [I] market ┌ Resolution step
2024-07-14 04:45:00 [I] market - @koishijs/plugin-sandbox@npm:3.3.1
2024-07-14 04:45:00 [I] market └ Completed
2024-07-14 04:45:00 [I] market ┌ Post-resolution validation
2024-07-14 04:45:00 [I] market └ Completed
2024-07-14 04:45:00 [I] market ┌ Fetch step
2024-07-14 04:45:00 [I] market └ Completed in 0s 290ms
2024-07-14 04:45:00 [I] market ┌ Link step
2024-07-14 04:45:00 [I] market └ Completed in 0s 302ms
2024-07-14 04:45:06 [I] loader apply plugin marisa-reply:qiowpl
2024-07-14 04:46:12 [W] command fs-tts a
                        Error: code 1006
                            at coerce (/koishi/node_modules/@koishijs/utils/lib/index.cjs:90:72)
                            at Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1137:46)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2162:22
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2065:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:853:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:853:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:853:16)
                            at async Processor._handleMessage (/koishi/node_modules/@koishijs/core/lib/index.cjs:864:22)
```

**Comment by idranme** [comment]
Duplicate of #4
